services:
  web:
    image: ghcr.io/thadeu/voodu-webui:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      RAILS_ENV: production
      METRICS_WAREHOUSE: 1
    volumes:
      - voodu_webui_storage:/rails/storage

volumes:
  voodu_webui_storage:

network:
  default:
    name: voodu_webui_network
