# frozen_string_literal: true

# AddKeyToServers — every Server gets a short, URL-safe key.
#
# Why a separate `key` column instead of using the existing id (or a UUID)?
#
#   - `id` is a sequential integer; surfacing it in the URL leaks the
#     count of registered servers and is enumerable.
#   - A full UUID is 36 chars and ugly in the URL bar:
#         /550e8400-e29b-41d4-a716-446655440000/pods
#   - 6-char base62 is 56 bits of entropy (collision-resistant up to
#     ~10^8 rows — comfortably beyond a single operator's server count)
#     and keeps URLs scannable:
#         /a3f9k2/pods
#
# Backfill: existing rows get a key generated by the Server model
# during the same migration. New rows pick one up via after_create_commit.
class AddKeyToServers < ActiveRecord::Migration[8.1]
  def up
    add_column :servers, :key, :string

    # Backfill before adding the NOT NULL + unique constraints —
    # collision-free since each call to Server.generate_unique_key
    # checks the table for existing keys.
    Server.reset_column_information

    Server.find_each do |server|
      server.update_column(:key, Server.generate_unique_key)
    end

    change_column_null :servers, :key, false
    add_index :servers, :key, unique: true
  end

  def down
    remove_index :servers, :key
    remove_column :servers, :key
  end
end
