# frozen_string_literal: true

# AddKeyToIslands — every Island gets a short, URL-safe key.
#
# Why a separate `key` column instead of using the existing id (or a UUID)?
#
#   - `id` is a sequential integer; surfacing it in the URL leaks the
#     count of registered islands and is enumerable.
#   - A full UUID is 36 chars and ugly in the URL bar:
#         /550e8400-e29b-41d4-a716-446655440000/pods
#   - 6-char base62 is 56 bits of entropy (collision-resistant up to
#     ~10^8 rows — comfortably beyond a single operator's island count)
#     and keeps URLs scannable:
#         /a3f9k2/pods
#
# Backfill: existing rows get a key generated by the Island model
# during the same migration. New rows pick one up via after_create_commit.
class AddKeyToIslands < ActiveRecord::Migration[8.1]
  def up
    add_column :islands, :key, :string

    # Backfill before adding the NOT NULL + unique constraints —
    # collision-free since each call to Island.generate_unique_key
    # checks the table for existing keys.
    Island.reset_column_information

    Island.find_each do |island|
      island.update_column(:key, Island.generate_unique_key)
    end

    change_column_null :islands, :key, false
    add_index :islands, :key, unique: true
  end

  def down
    remove_index :islands, :key
    remove_column :islands, :key
  end
end
