# frozen_string_literal: true

# Island represents one voodu controller the WebUI talks to.
#
# Each Island carries:
#
#   - `name`     — operator-supplied label (sidebar display).
#   - `endpoint` — full URL of the controller's PAT plane,
#                  e.g. `http://203.0.113.10:8687`.
#   - `pat`      — the Personal Access Token used in
#                  `Authorization: Bearer <pat>`. Stored encrypted at
#                  rest via ActiveRecord Encryption.
#
# Static helpers (`host`, `pods_count`, `status`) feed the sidebar
# row without going to the network — `pods_count` is a cheap derived
# field cached in the future; for M3 it returns 0 (M4 caches live).
class Island < ApplicationRecord
  # Default voodu observability-plane port. The operator usually only
  # types the IP; we splice this in if no explicit port is present.
  DEFAULT_PORT = 8687

  # ActiveRecord Encryption — Rails encrypts the column at write,
  # decrypts on read. Operator never has to think about it.
  encrypts :pat_ciphertext

  before_validation :normalize_endpoint

  validates :name, presence: true, uniqueness: true, length: { maximum: 64 }
  validates :endpoint, presence: true, format: {
    with: %r{\Ahttps?://[^/]+:\d+}, message: "could not be normalised to scheme://host:port"
  }
  validates :pat_ciphertext, presence: true

  # Convenience accessor — read/write as `island.pat` even though
  # the column is named pat_ciphertext (the name tells anyone reading
  # the schema "this is encrypted, don't grep for the plaintext").
  alias_attribute :pat, :pat_ciphertext

  # Extracts the host:port portion of the endpoint for sidebar display.
  # `http://203.0.113.10:8687` → `203.0.113.10:8687`.
  def host
    URI.parse(endpoint).then { |u| [u.host, u.port].compact.join(":") }
  rescue URI::InvalidURIError
    endpoint
  end

  # pods_count — total pod count, read from a Rails.cache key
  # OverviewData warms after its /pods fetch. Returns nil when no
  # snapshot exists (e.g. operator has never opened the dashboard
  # for this island since boot) — sidebar renders "—" instead of a
  # misleading 0.
  #
  # Cache TTL slightly longer than the overview snapshot (10s) so
  # the sidebar mirrors the operator's freshest data without
  # briefly blanking out between page renders within a session.
  def pods_count
    Rails.cache.read(self.class.pods_count_cache_key(id))
  end

  # Class-level cache-key + writer so OverviewData (and any future
  # consumer) can warm the count by id alone, without needing an
  # Island instance. Same id-keyed pattern IslandHealth uses.
  def self.pods_count_cache_key(island_id)
    "voodu:pods_count:v1:island:#{island_id}"
  end

  def self.write_pods_count(island, count, ttl: 30.seconds)
    Rails.cache.write(pods_count_cache_key(island.id), count.to_i, expires_in: ttl)
  end

  # status — :online | :offline. Read from IslandHealth's cache.
  #
  # First read after cache expiry triggers a synchronous probe (one
  # HTTP round-trip to /api/pat/v1/system). With TTL 30s and typical
  # 1–3 islands per operator, this is negligible cost; the upside is
  # the sidebar and topbar show truth instead of a hardcoded :online.
  #
  # OverviewData.fetch! warms this cache as a side effect of its
  # /system call — so navigating the dashboard normally keeps the
  # status fresh without spending dedicated probes.
  def status
    IslandHealth.status_for(self)
  end

  # region — operator-supplied label rendered in the topbar chip
  # ("fra1", "us-east-1", "homelab"). Stored in its own column;
  # nil/blank means "operator didn't tag this island" and the
  # topbar omits the chip rather than fabricating one.
  #
  # No validation — operators use whatever vocabulary fits their
  # mental model. Two operators looking at the same VPS may give it
  # different labels and that's fine.
  #
  # The column reader is auto-generated by ActiveRecord; this
  # override exists only to surface "—" as a UI sentinel when the
  # value is blank (handy when the topbar needs SOMETHING to render
  # but the operator chose to leave the field empty).
  def region
    self[:region].presence || "—"
  end

  # infra — paired with region for the topbar's secondary chip
  # ("hetzner", "aws", "bare-metal"). Same conventions as region:
  # free-text, optional, no validation. The topbar renders both
  # next to each other when both are set; if one is blank the
  # other still shows on its own.
  def infra
    self[:infra].presence
  end

  # uptime — stale fallback derived from the Island record's
  # created_at, used only on pages that haven't fetched /system
  # (every page except Overview today). The Overview view passes
  # the LIVE uptime from OverviewData#uptime_label into the topbar
  # explicitly, overriding this method.
  #
  # The whole reason this still exists is so non-Overview pages
  # render SOMETHING in the chip rather than blank. Once every page
  # has a system snapshot, this can be removed.
  def uptime
    return "—" if created_at.nil?

    days = ((Time.current - created_at).to_i / 86_400).abs
    "#{days}d 0h"
  end

  private

  # normalize_endpoint — turn operator-friendly input into a fully-
  # qualified URL the HTTP client can consume.
  #
  # Accepted inputs (all normalise to `http://1.2.3.4:8687`):
  #
  #   1.2.3.4
  #   1.2.3.4:8687
  #   http://1.2.3.4
  #   http://1.2.3.4:8687
  #
  # Rules:
  #   - Missing scheme → prepend "http://" (operators don't think in
  #     schemes for an IP-addressable controller).
  #   - Missing explicit port → append ":#{DEFAULT_PORT}" right after
  #     the host. URI's "default scheme port" (80/443) does NOT count
  #     as explicit — we want the WebUI default of 8687 to win.
  #   - Custom port (e.g. operator firewalls the plane to a non-default
  #     port) → respected verbatim.
  def normalize_endpoint
    return if endpoint.blank?

    raw = endpoint.strip

    # 1. Ensure scheme.
    raw = "http://#{raw}" unless raw.match?(%r{\Ahttps?://})

    # 2. Ensure explicit port. Regex matches scheme + host (no path,
    # no query, no fragment, no `:` already). Inserts `:8687` right
    # before the path/end. We don't run unless no explicit :digits
    # appears in the authority component.
    has_port = raw.match?(%r{\Ahttps?://[^/?#]+:\d+})

    unless has_port
      raw = raw.sub(%r{\A(https?://[^/:?#]+)}, "\\1:#{DEFAULT_PORT}")
    end

    self.endpoint = raw
  rescue StandardError
    # Anything weird — leave the original value in place so the
    # format validator surfaces a clear error to the operator.
  end
end
