# frozen_string_literal: true

# Org — the account/grouping layer above servers. One Org groups N servers;
# from M1 on, Metrics + Alerts become org-level (a panel/alert can target any
# server in the org). Today there's no login — the Org is the isolation
# boundary, and a future Tenant layer (subdomain → N orgs) stays additive
# above it, no remodel.
#
# Identity: a UUIDv7 string PK (HasUuidV7) for global uniqueness + time
# ordering, plus a `short_id` (8-char base62) as the opaque URL handle used
# from M1 on. A server always belongs to exactly one Org (Server belongs_to
# :org, org_id null:false) — no orphan servers, no default org.
class Org < ApplicationRecord
  include HasUuidV7
  include UniqueShortKeyable

  # 8-char base62 handle for URLs (M1): URL-clean + hand-typeable, ~48 bits so
  # it's non-guessable at SaaS scale. Generated by UniqueShortKeyable below.
  unique_short_key :short_id, length: 8

  # restrict_with_error: deleting an Org that still owns servers is blocked
  # with a friendly error (mirrors the DB FK restrict) — the operator moves
  # or removes the servers first, so no server is left orphaned.
  has_many :servers, dependent: :restrict_with_error

  # Metric dashboards live at the org level (M2) — a dashboard's panels can
  # pull from any of the org's servers. Reaped with the org.
  has_many :metric_dashboards, dependent: :destroy

  # Alerts are org-level (M3): a rule targets any server in the org, events fire
  # against those servers, and destinations (webhooks) are shared org-wide.
  # Reaped with the org (which is itself blocked while it still owns servers).
  has_many :alert_rules, dependent: :destroy
  has_many :alert_events, dependent: :destroy
  has_many :alert_destinations, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: {maximum: 64}
  validates :short_id, presence: true, uniqueness: true, format: {with: /\A[a-zA-Z0-9]{8}\z/}

  # to_param — URLs use the opaque short_id (shorter than the uuid, still
  # non-guessable). The route constraint (M1) matches the 8-char shape.
  def to_param
    short_id
  end
end
